package anylife.androiddbmanger.entity.daoManger;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import anylife.androiddbmanger.entity.Classify;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLASSIFY".
*/
public class ClassifyDao extends AbstractDao<Classify, Long> {

    public static final String TABLENAME = "CLASSIFY";

    /**
     * Properties of entity Classify.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Created = new Property(1, long.class, "created", false, "CREATED");
        public final static Property Message = new Property(2, String.class, "message", false, "MESSAGE");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Classify = new Property(4, String.class, "classify", false, "CLASSIFY");
        public final static Property UnreadNum = new Property(5, long.class, "unreadNum", false, "UNREAD_NUM");
    }


    public ClassifyDao(DaoConfig config) {
        super(config);
    }
    
    public ClassifyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLASSIFY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CREATED\" INTEGER NOT NULL ," + // 1: created
                "\"MESSAGE\" TEXT," + // 2: message
                "\"TITLE\" TEXT," + // 3: title
                "\"CLASSIFY\" TEXT," + // 4: classify
                "\"UNREAD_NUM\" INTEGER NOT NULL );"); // 5: unreadNum
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLASSIFY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Classify entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCreated());
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(3, message);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String classify = entity.getClassify();
        if (classify != null) {
            stmt.bindString(5, classify);
        }
        stmt.bindLong(6, entity.getUnreadNum());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Classify entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCreated());
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(3, message);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String classify = entity.getClassify();
        if (classify != null) {
            stmt.bindString(5, classify);
        }
        stmt.bindLong(6, entity.getUnreadNum());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Classify readEntity(Cursor cursor, int offset) {
        Classify entity = new Classify( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // created
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // message
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // classify
            cursor.getLong(offset + 5) // unreadNum
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Classify entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCreated(cursor.getLong(offset + 1));
        entity.setMessage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setClassify(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUnreadNum(cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Classify entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Classify entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Classify entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
