package anylife.androiddbmanger.entity.daoManger;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import anylife.androiddbmanger.entity.Classify;
import anylife.androiddbmanger.entity.Messages;
import anylife.androiddbmanger.entity.Note;

import anylife.androiddbmanger.entity.daoManger.ClassifyDao;
import anylife.androiddbmanger.entity.daoManger.MessagesDao;
import anylife.androiddbmanger.entity.daoManger.NoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig classifyDaoConfig;
    private final DaoConfig messagesDaoConfig;
    private final DaoConfig noteDaoConfig;

    private final ClassifyDao classifyDao;
    private final MessagesDao messagesDao;
    private final NoteDao noteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        classifyDaoConfig = daoConfigMap.get(ClassifyDao.class).clone();
        classifyDaoConfig.initIdentityScope(type);

        messagesDaoConfig = daoConfigMap.get(MessagesDao.class).clone();
        messagesDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        classifyDao = new ClassifyDao(classifyDaoConfig, this);
        messagesDao = new MessagesDao(messagesDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);

        registerDao(Classify.class, classifyDao);
        registerDao(Messages.class, messagesDao);
        registerDao(Note.class, noteDao);
    }
    
    public void clear() {
        classifyDaoConfig.clearIdentityScope();
        messagesDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
    }

    public ClassifyDao getClassifyDao() {
        return classifyDao;
    }

    public MessagesDao getMessagesDao() {
        return messagesDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

}
